/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airbangla;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahady Hasan Fahim
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    

    public GUI() {
         slection=new LinkedList<Selection>();
        initComponents();
        dashboard.setVisible(true);       	
        buy.setVisible(false);
        login.setVisible(false);
        sigup.setVisible(false);
        afterLogin.setVisible(false);
        
        users=new LinkedList<User>();
        users.add(new User("Mahady","1","Mahady","fmahady01@gmail.com","11"));
        users.add(new User("Fahim","1","Fahim","fmahady000@gmail.com","11"));
        users.add(new User("1","1","Hasan","fmahady85@gmail.com","11"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JLayeredPane();
        login = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pas = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        afterLogin = new javax.swing.JLayeredPane();
        buy = new javax.swing.JLayeredPane();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cobo1 = new javax.swing.JComboBox<>();
        cobo2 = new javax.swing.JComboBox<>();
        cobo4 = new javax.swing.JComboBox<>();
        cobo3 = new javax.swing.JComboBox<>();
        Total = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        vip = new javax.swing.JLabel();
        sigup = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        suName = new javax.swing.JTextField();
        suEmail = new javax.swing.JTextField();
        suUsername = new javax.swing.JTextField();
        suPassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        suSighpBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        pasportid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 600));

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        login.setBackground(new java.awt.Color(153, 0, 0));
        login.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        login.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Username:");

        us.setBorder(javax.swing.BorderFactory.createLineBorder(null, null));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Password:");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("BankGothic Md BT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Login");

        jButton7.setText("Dashboard");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        login.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        login.setLayer(us, javax.swing.JLayeredPane.DEFAULT_LAYER);
        login.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        login.setLayer(pas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        login.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        login.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        login.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(654, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(495, Short.MAX_VALUE))
        );

        afterLogin.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout afterLoginLayout = new javax.swing.GroupLayout(afterLogin);
        afterLogin.setLayout(afterLoginLayout);
        afterLoginLayout.setHorizontalGroup(
            afterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        afterLoginLayout.setVerticalGroup(
            afterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        buy.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Welcome to Air Bangla");

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("   Login   ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SignUp");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Login  for Your Travel details");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("SignUp for make Profile");

        cobo1.setBackground(new java.awt.Color(153, 255, 255));
        cobo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Place Selection-", "Dhaka to Mymensingh", "Dhaka to Barishal", "Dhaka to Rangpur", "Dhaka to Syllet", "Dhaka to Rajshahi", "Dhaka to Khulna", "Dhaka to Chottogram", "Dhaka to Cox'sBazar", "Dhaka to Josshor" }));
        cobo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobo1ActionPerformed(evt);
            }
        });

        cobo2.setBackground(new java.awt.Color(153, 255, 255));
        cobo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Select Time ->", "12 am", "01 am", "02 am", "03 am", "04 am", "05 am", "006 am", "7 am", "08 am", "09 am", "10 am", "11 am", "12 pm", "01 pm ", "02 pm", "03 pm", "04 pm", "05 pm", "06 pm", "07 pm", "08 pm", "09 pm", "10 pm", "11 pm" }));
        cobo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobo2ActionPerformed(evt);
            }
        });

        cobo4.setBackground(new java.awt.Color(153, 255, 255));
        cobo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Ticket Nmber->", "Ticket Nmber-> 01", "Ticket Nmber-> 02", "Ticket Nmber-> 03", "Ticket Nmber-> 04", "Ticket Nmber-> 05", "Ticket Nmber-> 06" }));
        cobo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobo4ActionPerformed(evt);
            }
        });

        cobo3.setBackground(new java.awt.Color(153, 255, 255));
        cobo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Class->", "Business Class", "Economic Class" }));
        cobo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobo3ActionPerformed(evt);
            }
        });

        Total.setBackground(new java.awt.Color(102, 0, 102));
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("BUY");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        id.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Passport number");

        jButton6.setBackground(new java.awt.Color(102, 0, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Total");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        vip.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buy.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(cobo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(cobo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(cobo4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(cobo3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(Total, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(price, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buy.setLayer(vip, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout buyLayout = new javax.swing.GroupLayout(buy);
        buy.setLayout(buyLayout);
        buyLayout.setHorizontalGroup(
            buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyLayout.createSequentialGroup()
                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(486, 486, 486))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(524, 524, 524)))
                        .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(buyLayout.createSequentialGroup()
                        .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buyLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buyLayout.createSequentialGroup()
                                .addGap(485, 485, 485)
                                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(buyLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(buyLayout.createSequentialGroup()
                                            .addGap(288, 288, 288)
                                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(buyLayout.createSequentialGroup()
                                            .addComponent(vip, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(buyLayout.createSequentialGroup()
                                        .addComponent(cobo1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(cobo2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(cobo3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(cobo4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buyLayout.setVerticalGroup(
            buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobo3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobo4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(buyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vip, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(423, 423, 423)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sigup.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Username:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Password:");

        suName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        suName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        suName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        suEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        suEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        suEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        suUsername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        suUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        suUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        suPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        suPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        suPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton2.setBackground(new java.awt.Color(51, 0, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        suSighpBtn.setBackground(new java.awt.Color(51, 0, 51));
        suSighpBtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        suSighpBtn.setForeground(new java.awt.Color(255, 255, 255));
        suSighpBtn.setText("SignUp");
        suSighpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suSighpBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Passport Number");

        pasportid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pasportid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        pasportid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        sigup.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(suName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(suEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(suUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(suPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(suSighpBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sigup.setLayer(pasportid, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sigupLayout = new javax.swing.GroupLayout(sigup);
        sigup.setLayout(sigupLayout);
        sigupLayout.setHorizontalGroup(
            sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sigupLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sigupLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasportid, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(sigupLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(suName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sigupLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(suSighpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(sigupLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(suEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sigupLayout.createSequentialGroup()
                            .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(suUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(suPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(725, Short.MAX_VALUE))
        );
        sigupLayout.setVerticalGroup(
            sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sigupLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sigupLayout.createSequentialGroup()
                        .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sigupLayout.createSequentialGroup()
                        .addComponent(suUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(suPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasportid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sigupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(suSighpBtn)
                        .addComponent(jButton2)))
                .addContainerGap(478, Short.MAX_VALUE))
        );

        suName.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(363, 363, 363)
                    .addComponent(afterLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buy, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 92, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(sigup, javax.swing.GroupLayout.PREFERRED_SIZE, 1171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(346, 346, 346)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(afterLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buy, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sigup, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        sigup.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cobo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobo2ActionPerformed
        // TODO add your handling code here:
         b=cobo2.getSelectedIndex();
         selectionCombo2=cobo2.getSelectedItem().toString();
    }//GEN-LAST:event_cobo2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //login
dashboard.setVisible(false);       	
buy.setVisible(false);
login.setVisible(true);
sigup.setVisible(false);
afterLogin.setVisible(false);
        

        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
dashboard.setVisible(false);       	
buy.setVisible(false);
login.setVisible(false);
sigup.setVisible(true);
afterLogin.setVisible(false);
 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // singuun dashboard lougout
        
dashboard.setVisible(false);       	
buy.setVisible(false);
login.setVisible(true);
sigup.setVisible(false);
afterLogin.setVisible(false);
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void suSighpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suSighpBtnActionPerformed
        
        String name,password,email,username,passo;
        name=suName.getText();
        email=suEmail.getText();
        username=suUsername.getText();
        password=suPassword.getText();
        passo=pasportid.getText();
        
        
        if (name.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Name field is empty.");
} else if (email.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Email field is empty.");
} else if (username.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Username field is empty.");
} else if (password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Password field is empty.");
} else if (passo.isEmpty()) {
    JOptionPane.showMessageDialog(this, "passport field is empty.");
}

else {
   int result = JOptionPane.showConfirmDialog(null, "Do you confirm?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);

   
if (result == JOptionPane.YES_OPTION) {
    JOptionPane.showMessageDialog(null, "You confirmed.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
} else if (result == JOptionPane.NO_OPTION) {
    JOptionPane.showMessageDialog(null, "You did not confirm.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
} else if (result == JOptionPane.CANCEL_OPTION) {
    JOptionPane.showMessageDialog(null, "You canceled.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
} else if (result == JOptionPane.CLOSED_OPTION) {
    JOptionPane.showMessageDialog(null, "Dialog closed without selection.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
}
else {
    JOptionPane.showMessageDialog(null, "OK button clicked.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
}
         users.add(new User(username,password,name,email,passo));
         
dashboard.setVisible(false);       	
buy.setVisible(false);
login.setVisible(true);
sigup.setVisible(false);
afterLogin.setVisible(false);
}
     
       
    }//GEN-LAST:event_suSighpBtnActionPerformed

    private void cobo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobo1ActionPerformed
        // TODO add your handling code here:
        
        //1st combo box 
       selectionCombo1=cobo1.getSelectedItem().toString();
       a=cobo1.getSelectedIndex();
        
        
    }//GEN-LAST:event_cobo1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
dashboard.setVisible(true);       	
buy.setVisible(false);
login.setVisible(false);
sigup.setVisible(false);
afterLogin.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

       
        
        
            String username=us.getText();
            String password=String.valueOf(pas.getPassword());

        for (User user : users) {
            if(user.macthuser(username)){

            }if(user.matchpass(password)){
                
dashboard.setVisible(false);       	
buy.setVisible(true);
login.setVisible(false);
sigup.setVisible(false);
afterLogin.setVisible(false);
dis=1;
       
                
                
            }else{

                JOptionPane.showMessageDialog(this, "Invalid","Invaild Password",JOptionPane.ERROR_MESSAGE);
             
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cobo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobo3ActionPerformed
        // TODO add your handling code here:
         selectionCombo3=cobo3.getSelectedItem().toString();
          c=cobo3.getSelectedIndex();
    }//GEN-LAST:event_cobo3ActionPerformed

    private void cobo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobo4ActionPerformed
        // TODO add your handling code her
     selectionCombo4=cobo4.getSelectedItem().toString();
      d=cobo4.getSelectedIndex();
    }//GEN-LAST:event_cobo4ActionPerformed
private int total(){
     ft=0;
        if(a==1){
            
        }
        else if(a==2){
            ft=100;
        }else if(a==3){
            ft=110;
        }else if(a==4){
            ft=120;
        }else if(a==5){
            ft=121;
        }else if(a==6){
            ft=90;
        }else if(a==7){
            ft=130;
        }else if(a==8){
            ft=111;
        }else if(a==9){
            ft=109;
        }
        return (ft*c)*d;
    
}
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        

        total=total();
        if(dis==1){
            total=total-20;
        }
        vip.setText("You are VIP your discount is 20$");
        price.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        /////////////
        //////////

        price.setText(selectionCombo1);
        ids=id.getText();
        String ta=Integer.toString(total);
        
        if (ids.isEmpty()) {
    JOptionPane.showMessageDialog(this, "You Must give your pasport number");
}

     
        slection.add(new Selection(selectionCombo1,selectionCombo2,selectionCombo3,selectionCombo4,ids,ta));

    }//GEN-LAST:event_TotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    private LinkedList<User>users;
  
    private LinkedList<Selection>slection;
     String selectionCombo1,selectionCombo2,selectionCombo3,selectionCombo4,ids;
     int a,b,c,d,total,ft,dis;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Total;
    private javax.swing.JLayeredPane afterLogin;
    private javax.swing.JLayeredPane buy;
    private javax.swing.JComboBox<String> cobo1;
    private javax.swing.JComboBox<String> cobo2;
    private javax.swing.JComboBox<String> cobo3;
    private javax.swing.JComboBox<String> cobo4;
    private javax.swing.JLayeredPane dashboard;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane login;
    private javax.swing.JPasswordField pas;
    private javax.swing.JTextField pasportid;
    private javax.swing.JLabel price;
    private javax.swing.JLayeredPane sigup;
    private javax.swing.JTextField suEmail;
    private javax.swing.JTextField suName;
    private javax.swing.JTextField suPassword;
    private javax.swing.JButton suSighpBtn;
    private javax.swing.JTextField suUsername;
    private javax.swing.JTextField us;
    private javax.swing.JLabel vip;
    // End of variables declaration//GEN-END:variables
}
